spring:
  datasource:
    url: jdbc:postgresql://esante-postgres:5432/patient_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://esante-registry:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
