spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: patient-service
          uri: lb://ESANTE-PATIENT-SERVICE
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            
        - id: consultation-service
          uri: lb://ESANTE-CONSULTATION-SERVICE
          predicates:
            - Path=/api/consultations/**
          filters:
            - StripPrefix=1
            
        - id: auth-service
          uri: lb://ESANTE-AUTHENTIFICATION-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
            
        - id: laboratoire-service
          uri: lb://ESANTE-LABORATOIRE-SERVICE
          predicates:
            - Path=/api/analyses/**
          filters:
            - StripPrefix=1
            
        - id: facturation-service
          uri: lb://ESANTE-FACTURATION-SERVICE
          predicates:
            - Path=/api/factures/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://esante-registry:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
